/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html', './about/*.html', './src/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#930006',
        'on-secondary': '#ffffff',
        surface: '#fcf9f8',
        outline: '#8f706b',
        'on-background': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474742',
        'error-container': '#ffdad6',
        'primary-container': '#d9372d',
        'on-secondary-fixed-variant': '#474747',
        'on-surface': '#1c1b1b',
        background: '#fcf9f8',
        'inverse-on-surface': '#f3f0ef',
        'surface-container': '#f0eded',
        'on-tertiary-container': '#fdffdd',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e5e2e1',
        tertiary: '#5d5c57',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#e5e2db',
        'surface-container-high': '#eae7e7',
        'secondary-container': '#e2e2e2',
        'outline-variant': '#e4beb9',
        'primary-fixed-dim': '#ffb4aa',
        'on-tertiary-fixed': '#1c1c18',
        'secondary-fixed': '#e2e2e2',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'surface-dim': '#dcd9d9',
        'tertiary-container': '#76756f',
        'on-secondary-container': '#646464',
        'secondary-fixed-dim': '#c6c6c6',
        'on-primary-fixed': '#410001',
        'on-error': '#ffffff',
        'surface-container-highest': '#e5e2e1',
        'on-primary': '#ffffff',
        'surface-tint': '#b91e19',
        'on-surface-variant': '#5b403c',
        'surface-bright': '#fcf9f8',
        'inverse-surface': '#313030',
        'inverse-primary': '#ffb4aa',
        secondary: '#5e5e5e',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffdad5',
        primary: '#e03c31',
        'tertiary-fixed-dim': '#c9c6c0',
        'surface-container-low': '#f6f3f2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'element-gap': '32px',
        'section-gap': '120px',
        'margin-mobile': '20px',
        gutter: '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk'],
        'display-lg': ['Old Standard TT'],
        'label-mono': ['Space Grotesk'],
        'label-caps': ['Space Grotesk'],
        'headline-md': ['Old Standard TT'],
        'headline-lg': ['Old Standard TT'],
        'body-md': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Old Standard TT'],
        cjk: ['Noto Serif SC', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': [
          '84px',
          { lineHeight: '92px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-mono': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' },
        ],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '32px',
          { lineHeight: '38px', fontWeight: '600' },
        ],
        xs: '14px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
